[project]
name = "moccasin_project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mamushi>=0.0.5",
    "moccasin>=0.4.2",
    "ruff>=0.12.1",
    "rust-just>=1.40.0",
    "titanoboa>=0.2.7",
]
